### ISSUE TITLE
LGMTとは何なのか

### ISSUE THREAD

**Issue by kokokokokokokokokokoko** [apckane/github-flow-test-201805#40]

**Comment by ryo-yamaoka** [comment]
「俺はいいと思う」的な略語

http://d.hatena.ne.jp/keyword/LGTM

**Comment by ikegami0413** [comment]
"Looks Good To Me”の略らしいです。[https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwjfz53Bzd_dAhUKv7wKHVIeDFkQjRx6BAgBEAU&url=https%3A%2F%2Fqiita.com%2Ftos-miyake%2Fitems%2F7e33b67fc62620d4e87b&psig=AOvVaw2hFOYiK08dAX1ajSQL74eK&ust=1538288651793656](url)
